# name: Deploy Frontend

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up SSH
#         uses: webfactory/ssh-agent@v0.5.3
#         with:
#           ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

#       - name: Deploy Frontend
#         env:
#           SERVER_IP: ${{ secrets.SERVER_IP }}
#           SERVER_USER: ${{ secrets.SERVER_USER }}
#         run: |
#           ssh -o StrictHostKeyChecking=no $SERVER_USER@$SERVER_IP << 'EOF'
#             set -e  # Остановить выполнение при любой ошибке
            
#             echo "Navigating to project directory..."
#             cd ~/manage-hambax

#             echo "Stopping and removing existing frontend container..."
#             docker-compose down || true

#             echo "Removing old Docker images..."
#             docker rmi $(docker images -q) -f || true

#             echo "Pulling latest code..."
#             git pull origin main

#             echo "Building new Docker image..."
#             docker-compose build --no-cache

#             echo "Starting frontend container..."
#             docker-compose up -d --build

#             echo "Cleaning up unused Docker images..."
#             docker image prune -f

#             echo "Deployment completed successfully!"
#           EOF
